import { TASK_KEY } from '../shared/constants.js';
import { consumePreviewTask } from '../background/preview-task.js';
import { planCapturePositions, resolveCaptureY } from '../shared/capture.js';
import { toImageCrop } from '../shared/region.js';
import { scaledDimensions, planResolutionSlices, exportFilename } from '../shared/resolution.js';
import { findHorizontalContentBounds } from '../shared/trim-background.js';
import { captureProgress } from '../shared/progress.js';
import { copyCanvas, downloadCanvas, errorMessage } from './export-actions.js';
import { downloadRenderedSlices, renderDocumentSlices } from './document-renderer.js';
const taskId=new URLSearchParams(location.search).get('taskId');let task;const canvas=document.querySelector('#canvas');const status=document.querySelector('#status');let finalCanvas;
const show=(t,e=false)=>{status.textContent=t;status.className=`status${e?' error':''}`};
function renderDocument(doc){document.querySelector('#mode').textContent=doc.mode==='ai'?'AI 智能提取':'传统提取';document.querySelector('#title').textContent=doc.title;document.querySelector('#summary').textContent=doc.summary||'';const root=document.querySelector('#content');root.replaceChildren();for(const section of doc.sections){const wrap=document.createElement('section');if(section.heading){const h=document.createElement('h2');h.contentEditable='true';h.textContent=section.heading;wrap.append(h);}for(const value of section.paragraphs){const p=document.createElement('p');p.contentEditable='true';p.textContent=value;wrap.append(p);}if(section.bullets.length){const ul=document.createElement('ul');for(const value of section.bullets){const li=document.createElement('li');li.contentEditable='true';li.textContent=value;ul.append(li);}wrap.append(ul);}for(const image of section.images){const img=document.createElement('img');img.src=image.src;img.alt=image.alt;img.referrerPolicy='no-referrer';img.addEventListener('error',()=>img.remove());wrap.append(img);}root.append(wrap);}document.querySelector('#source').textContent=`来源：${doc.source.title} · ${doc.source.url}`;}
function showCapturePreview(capturedCanvas){document.body.classList.add('capture-mode');document.querySelector('#mode').textContent='完整导出 · 整个页面';const preview=capturedCanvas;preview.className='capture-preview';canvas.replaceChildren(preview);canvas.removeAttribute('data-theme');canvas.style.width='auto';canvas.style.padding='0';show('整页捕获完成，可下载或复制图片');refreshResolutionHint();}
function trimHorizontalCanvas(source){const sample=document.createElement('canvas');const scale=Math.min(1,800/source.width,800/source.height);sample.width=Math.max(1,Math.round(source.width*scale));sample.height=Math.max(1,Math.round(source.height*scale));sample.getContext('2d').drawImage(source,0,0,sample.width,sample.height);const bounds=findHorizontalContentBounds(sample.getContext('2d').getImageData(0,0,sample.width,sample.height));const left=Math.round(bounds.left/scale);const right=Math.round(bounds.right/scale);if(left<8&&source.width-right<8)return source;const output=document.createElement('canvas');output.width=Math.max(1,right-left);output.height=source.height;output.getContext('2d').drawImage(source,left,0,output.width,source.height,0,0,output.width,source.height);return output;}
async function fullCapture(){show('正在捕获整页，请不要切换标签页…');const {tabId,metrics}=task;const positions=planCapturePositions(metrics.height,metrics.viewportHeight);const frames=[];let completed=false;await chrome.tabs.sendMessage(tabId,{type:'BEGIN_FULL_CAPTURE_PROGRESS',total:positions.length});try{for(const [index,y] of positions.entries()){const progress=captureProgress(index+1,positions.length);const activated=await chrome.runtime.sendMessage({type:'ACTIVATE_CAPTURE_TAB',tabId});if(!activated?.ok)throw new Error(activated?.error||'无法激活待导出页面');const moved=await chrome.tabs.sendMessage(tabId,{type:'SCROLL_TO',y,current:progress.current,total:progress.total});const r=await chrome.runtime.sendMessage({type:'CAPTURE_TAB_FRAME',tabId});if(!r.ok)throw new Error(r.error);frames.push({y:resolveCaptureY(y,moved),url:r.dataUrl});await chrome.tabs.sendMessage(tabId,{type:'CAPTURE_FRAME_DONE',current:progress.current,total:progress.total});}const ratio=(await load(frames[0].url)).width/metrics.width;finalCanvas=document.createElement('canvas');finalCanvas.width=Math.round(metrics.width*ratio);finalCanvas.height=Math.round(metrics.height*ratio);const ctx=finalCanvas.getContext('2d');for(const f of frames){const img=await load(f.url);ctx.drawImage(img,0,Math.round(f.y*ratio));}finalCanvas=trimHorizontalCanvas(finalCanvas);await chrome.tabs.sendMessage(tabId,{type:'END_FULL_CAPTURE_PROGRESS'});completed=true;showCapturePreview(finalCanvas);await chrome.runtime.sendMessage({type:'ACTIVATE_SENDER'});}catch(error){await chrome.tabs.sendMessage(tabId,{type:'FAIL_FULL_CAPTURE_PROGRESS',error:errorMessage(error,'整页导出失败，请回到原页面后重试')}).catch(()=>{});throw error;}finally{await chrome.tabs.sendMessage(tabId,{type:'RESTORE_SCROLL',y:metrics.scrollY}).catch(()=>{});if(!completed)show('整页导出失败，请回到原页面后重试',true);}}
async function regionCapture(){show('正在生成框选预览…');const image=await load(task.dataUrl);const crop=toImageCrop(task.rect,task.viewport,{width:image.width,height:image.height});finalCanvas=document.createElement('canvas');finalCanvas.width=crop.width;finalCanvas.height=crop.height;finalCanvas.getContext('2d').drawImage(image,crop.x,crop.y,crop.width,crop.height,0,0,crop.width,crop.height);showCapturePreview(finalCanvas);document.querySelector('#mode').textContent='完整导出 · 自由框选';}
const load=url=>new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=url;});
function articleRenderStyle(){const dark=canvas.dataset.theme==='dark';return `<style>*{box-sizing:border-box}article{width:${canvas.offsetWidth}px;min-height:${canvas.scrollHeight}px;padding:72px 82px;background:${dark?'#17191f':'#fff'};color:${dark?'#f4f5f8':'#1b1d22'};font-family:Arial,sans-serif}h1{font-size:48px;line-height:1.15;margin:0 0 24px}.summary{font-size:20px;line-height:1.7;color:#676c78;border-left:4px solid #6366f1;padding-left:20px}h2{font-size:28px;margin-top:42px}p,li{font-size:18px;line-height:1.85}img{max-width:100%;border-radius:10px;margin:18px 0}footer{border-top:1px solid #9995;margin-top:48px;padding-top:16px;font-size:13px;opacity:.65}</style>`;}
async function outputCanvases(onSlice){const targetWidth=Number(document.querySelector('#width').value);if(!finalCanvas)return renderDocumentSlices({sourceWidth:canvas.offsetWidth,sourceHeight:canvas.scrollHeight,targetWidth,html:canvas.innerHTML,style:articleRenderStyle(),loadImage:load,createCanvas:(width,height)=>{const output=document.createElement('canvas');output.width=width;output.height=height;return output;},onSlice});const source=finalCanvas;const size=scaledDimensions(source.width,source.height,targetWidth);const slices=planResolutionSlices(size.height);if(slices.length===1&&source.width===size.width)return[source];const scale=size.width/source.width;return slices.map(slice=>{const output=document.createElement('canvas');output.width=size.width;output.height=slice.height;const sourceY=slice.y/scale;const sourceHeight=slice.height/scale;output.getContext('2d').drawImage(source,0,sourceY,source.width,sourceHeight,0,0,size.width,slice.height);return output;});}
function refreshResolutionHint(){const source=finalCanvas||canvas;const width=Number(document.querySelector('#width').value);const size=scaledDimensions(source.width||source.offsetWidth,source.height||source.scrollHeight,width);const slices=planResolutionSlices(size.height);const hint=document.querySelector('#resolutionHint');const megaPixels=Math.round(size.width*size.height/100000)/10;hint.textContent=`预计 ${size.width} × ${size.height} px · ${megaPixels} MP${slices.length>1?` · 将分为 ${slices.length} 张`:''}`;hint.classList.toggle('warning',megaPixels>60||slices.length>1);}
document.querySelector('#width').addEventListener('change',e=>{if(!finalCanvas)canvas.style.width=`${e.target.value}px`;refreshResolutionHint();});document.querySelector('#theme').addEventListener('change',e=>canvas.dataset.theme=e.target.value);document.querySelector('#images').addEventListener('change',e=>document.querySelectorAll('article img').forEach(i=>i.hidden=!e.target.checked));
const downloadButton=document.querySelector('#download');downloadButton.addEventListener('click',async()=>{downloadButton.disabled=true;try{show('正在生成图片…');const outputs=await outputCanvases((current,total)=>show(`正在生成第 ${current}/${total} 张…`));const width=Number(document.querySelector('#width').value);const stamp=Date.now();await downloadRenderedSlices(outputs,{onProgress:(current,total)=>show(`正在下载第 ${current}/${total} 张…`),download:(output,index,total)=>downloadCanvas(output,exportFilename(width,index,total,stamp))});const totalHeight=outputs.reduce((sum,output)=>sum+output.height,0);show(`图片已生成：${width} × ${totalHeight} px${outputs.length>1?`，共 ${outputs.length} 张`:''}`);}catch(e){show(`导出失败：${errorMessage(e,'浏览器无法生成导出图片，请降低分辨率或关闭部分图片后重试')}`,true);}finally{downloadButton.disabled=false;}});document.querySelector('#copy').addEventListener('click',async()=>{try{const outputs=await outputCanvases();if(outputs.length>1)throw new Error('超高清长图已自动分片，请使用“下载 PNG”');const c=outputs[0];await copyCanvas(c,{clipboard:navigator.clipboard,ClipboardItemCtor:globalThis.ClipboardItem});show(`图片已复制：${c.width} × ${c.height} px`);}catch(e){show(`复制失败：${errorMessage(e,'复制图片失败，请使用“下载 PNG”')}`,true);}});
async function initializePreview(preparedTask){task=preparedTask;if(task.kind==='fullCapture')await fullCapture();else if(task.kind==='regionCapture')await regionCapture();else if(task.document){renderDocument(task.document);refreshResolutionHint();}else throw new Error('预览任务已过期');}
try{await consumePreviewTask(chrome.storage.session,TASK_KEY,taskId,initializePreview);}catch(e){show(errorMessage(e,'预览任务初始化失败，请重试'),true);}
